config/routes.rb
Scrambled::Application.routes.draw do
  get "ranked_golfer/index"
  get "ranked_golfer/reset"
  devise_for :admins
  devise_for :users

  resources :tournaments do
    collection do
      get 'upcoming'
      get 'current'
      get 'previous'
      get 'user_tournaments'
      get 'mine'
    end
    member do
      get 'uninvited_users'
      post 'invite_users'
      get 'freeze_golfers'
      get 'agolfers'
      get 'bgolfers'
      get 'cgolfers'
      get 'dgolfers'
      post 'update_invitation_with_golfers'
      get 'user_tournament_invitation'
      get 'standings'
    end
  end

  get 'invitation/accept/:id', to: 'accept_invitation#index', as: :accept_invitations
  get 'invitation/open', to: 'accept_invitation#open_user_invites', as: :open_user_invitations
  post 'invitation/accept_via_secret', to: 'accept_invitation#accept_via_secret', as: :accept_via_secret
  get 'rankings', to: 'ranked_golfer#index', as: :current_rankings
  get 'ranked_golfers', to: 'ranked_golfer#list'
  get 'reset_ranks', to: 'ranked_golfer#reset'
  get '/templates/:path.html' => 'templates#template', :constraints => {:path => /.+/}
  root :to => 'visitors#new'
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :picks_start, presence: true
  validates :picks_end, presence: true
  validates :par, presence: true, numericality: { only_integer: true, greater_than: 0 }


  belongs_to :admin
  has_many :tournament_invitations

  def golfers
    @golfers = TournamentGolfer.where(:tournament_id => self.id).order_by(:rank.asc)
  end

  def a_golfers
    TournamentGolfer.where(tournament_id: self.id).between(rank: 1..5)
  end

  def b_golfers
    TournamentGolfer.where(tournament_id: self.id).between(rank: 6..20)
  end

  def c_golfers
    TournamentGolfer.where(tournament_id: self.id).between(rank: 21..50)
  end

  def d_golfers
    TournamentGolfer.where(tournament_id: self.id).gte(rank: 51)
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  require 'mechanize'
  require 'net/http'
  require 'json'

  before_filter :authenticate_admin!, except: [:upcoming, :user_tournaments, :mine,
                                               :agolfers, :bgolfers, :cgolfers, :dgolfers, :user_tournament_invitation, :standings, :update_invitation_with_golfers
  ]
  before_action :set_tournament, only: [:show, :edit, :update, :destroy,
                                        :uninvited_users, :invite_users, :freeze_golfers,
                                        :agolfers, :bgolfers, :cgolfers, :dgolfers,
                                        :user_tournament_invitation, :update_invitation_with_golfers, :standings]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all.order(:start_date)
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    uninvited_users
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.admin = current_admin
    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tournament }
      else
        format.html { render action: 'new' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      @tournament.admin = current_admin
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end

  def upcoming
    @tournaments = Tournament.where("end_date >= ?", Time.now).order("start_date")
    render json: @tournaments
  end

  def previous
    @tournaments = Tournament.where("end_date <= ?", Time.now).order("start_date desc")
    render json: @tournaments
  end

  def current
    @tournaments = Tournament.where("start_date <= ? and end_date >= ?", Time.now, Time.now).order("start_date")
    render json: @tournaments
  end


  def mine

  end

  def user_tournaments
    if user_signed_in?
      tournaments = current_user.tournament_invitations.accepted.collect do |ti|
        ti.tournament.secret_code = "{it's a secret}"
        ti.tournament
      end
      render json: tournaments

    else
      render json: []
    end

  end

  def user_tournament_invitation
    if user_signed_in?
      invite = TournamentInvitation.find_by_tournament_id_and_user_id(params["id"], current_user.id)
      render json: invite
    end
  end

  def update_invitation_with_golfers
    invite_params = golfers_for_invitation_params

    invitation = TournamentInvitation.find_by_tournament_id_and_user_id(invite_params["tournament_id"], current_user.id)

    if invitation && invitation.user == current_user
      invitation.agolfer = invite_params["agolfer"]
      invitation.bgolfer = invite_params["bgolfer"]
      invitation.cgolfer = invite_params["cgolfer"]
      invitation.dgolfer = invite_params["dgolfer"]
      invitation.save
      render json: invitation
    end
  end

  def agolfers
    render json: @tournament.a_golfers
  end

  def bgolfers
    render json: @tournament.b_golfers
  end

  def cgolfers
    render json: @tournament.c_golfers
  end

  def dgolfers
    render json: @tournament.d_golfers
  end

  def freeze_golfers
    golfers = RankedGolfer.all
    TournamentGolfer.delete_all(tournament_id: @tournament.id)
    if @tournament.leaderboard_url.ends_with? 'json'
      current_scores = get_json_scores @tournament
    else
      current_scores = get_scores @tournament
    end
    golfers.each do |g|
      if current_scores.has_key?(g.player)
        tg = TournamentGolfer.new
        tg.player = g.player
        tg.rank = g.rank
        tg.tournament_id = @tournament.id
        tg.save
      end
    end
    redirect_to @tournament, notice: "Golfers have been frozen"
  end

  def invite_users
    users = params[:invite].keys
    users.each do |u|
      begin
        user = User.find(u)
        ti = TournamentInvitation.new
        ti.tournament = @tournament
        ti.user = User.find(u)
        ti.save
        InvitationMailer.tournament_invitation(ti).deliver
      rescue Exception => e
        logger.error e.message
      end


    end
    redirect_to @tournament, notice: "Successfully sent invitations"
  end

  def uninvited_users
    @uninvited_users = User.all
    invited_users = @tournament.tournament_invitations.collect { |ti| ti.user }
    @uninvited_users -= invited_users
  end

  def standings
    all_invites = @tournament.tournament_invitations
    invites = []
    all_invites.each do |inv|
      invites << inv if (inv.accepted? and inv.agolfer)
    end
    @invites_plus_scores = []
    if @tournament.leaderboard_url.ends_with? 'json'
      current_scores = get_json_scores @tournament
    else
      current_scores = get_scores @tournament
    end
    invites.each do |i|
      invite = InviteWithScore.new(i)
      invite.agolferScore = current_scores[invite.agolfer]['total'] || 0
      invite.agolferStatus = current_scores[invite.agolfer]['status']

      invite.bgolferScore = current_scores[invite.bgolfer]['total'] || 0
      invite.bgolferStatus = current_scores[invite.bgolfer]['status']
      invite.cgolferScore = current_scores[invite.cgolfer]['total'] || 0
      invite.cgolferStatus = current_scores[invite.cgolfer]['status']
      invite.dgolferScore = current_scores[invite.dgolfer]['total'] || 0
      invite.dgolferStatus = current_scores[invite.dgolfer]['status']

      invite.agolferThru = current_scores[invite.agolfer]['thru']
      invite.bgolferThru = current_scores[invite.bgolfer]['thru']
      invite.cgolferThru = current_scores[invite.cgolfer]['thru']
      invite.dgolferThru = current_scores[invite.dgolfer]['thru']

      invite.totalScore = invite.totalScore
      @invites_plus_scores << invite
    end

    render json: @invites_plus_scores
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tournament_params
    params.require(:tournament).permit(:name, :message, :par, :start_date, :end_date, :picks_start, :picks_end, :secret_code, :leaderboard_url)
  end

  def golfers_for_invitation_params
    params.require(:picks).permit(:tournament_id, :agolfer, :bgolfer, :cgolfer, :dgolfer)
  end

  def get_scores(tournament)
    agent = Mechanize.new
    scores = {}
    agent.get(tournament.leaderboard_url) do |page|
      tbody = page.search("table.sportsTable tbody")
      rows = tbody.search("tr")
      rows.each do |row|
        score = {}
        next if row.search('.player').empty?
        name = row.search('.player').text.strip
        name = name.gsub('*', '') if name
        next if name =~ /started on/
        total_score_str = row.search(".total").text.strip
        # added
        strokes = row.search("td.total + td").text.strip # row.search("td")[9].text.strip
        # added
        third_round = row.search("td")[4].text.strip
        actual_score = 0
        actual_score = total_score_str.to_i unless total_score_str == '-' || total_score_str == 'E'
        # added
        actual_score = (strokes.to_i - (tournament.par * 2)) if ((third_round == 'CUT' || third_round == 'MC') && total_score_str == '-')
        scores[name] = actual_score
        scores[name] = 8 if name == 'Jason Dufner' && tournament.id == 4
        scores['Angel Cabrera'] = 15 if tournament.id == 4
        scores['Tiger Woods'] = 16 if tournament.id == 6
      end

    end
    scores
  end

  def get_json_scores(tournament)
    response = Net::HTTP.get_response(URI.parse(tournament.leaderboard_url))
    data = JSON.parse(response.body)
    scores = {}
    data['leaderboard']['players'].each do |player|
      name = "#{player['player_bio']['first_name']} #{player['player_bio']['last_name']}"
      score = {}
      score['total'] = player['total']
      score['status'] = player['status']
      score['thru']  = player['thru']
      scores[name] = score

    end
    scores
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<% unless @tournament.errors.messages.empty? %>
    <div class="alert alert-danger">
      Please fix the following errors:
      <ul>
      <% @tournament.errors.full_messages.each do |m| %>
           <li><%= m %></li>
      <% end %>
      </ul>
    </div>
<% end %>
<%= form_for(@tournament, html: {:class => "form-horizontal", :role => "form"}) do |f| %>

    <div class="form-group">
      <label class="col-sm-4 control-label" for="tournament[name]">Competition Name</label>
      <div class="col-sm-8">
        <%= f.text_field :name, :placeholder => "Name", :autofocus => true, :required => true %>
        <span class="help-block">(i.e. Masters 2014)</span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="start_date">Start Date</label>
      <div class="col-sm-8">
        <input type="date" name="tournament[start_date]" id="start_date" value="<%= @tournament.start_date %>" required>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="end_date">End Date</label>
      <div class="col-sm-8">
        <input type="date" name="tournament[end_date]" id="end_date" value="<%= @tournament.end_date %>"required>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="tournament_picks_start">Picking Start Date/Time</label>
      <div class="col-sm-8">
        <%= datetime_local_field :tournament, :picks_start, :required => true %>

        <span class="help-block">The date and time when people can start picking golfers</span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="tournament_picks_end">Picking End Date/Time</label>
      <div class="col-sm-8">
        <%= datetime_local_field :tournament, :picks_end, :required => true %>
        <span class="help-block">The cut-off date and time for picking golfers</span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="tournament[secret_code]">Secret Code</label>
      <div class="col-sm-8">
        <%= f.text_field :secret_code, :placeholder => "Secret Code", :required => true %>
        <span class="help-block">(If an invited user loses their email, they'll still be able to register for the tournament if they know the secret code)</span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="tournament[leaderboard_url]">Leaderboard URL</label>
      <div class="col-sm-8">
        <%= f.text_field :leaderboard_url, :placeholder => "URL", :required => true %>
        <span class="help-block">(e.g. http://sports.yahoo.com/golf/pga/leaderboard/2014/4)</span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="tournament[par]">Course Par</label>
      <div class="col-sm-8">
        <%= f.text_field :par, :placeholder => "72", :required => true %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="tournament[message]">Message</label>
      <div class="col-sm-8">
        <%= f.text_area :message, :cols => 80, :rows => 5, :placeholder => "A message to display with standings" %>
      </div>
    </div>

    <div class="form-group">
        <div class="col-sm-4"></div>
        <div class="col-sm-8">
        <button class="btn btn-lg btn-success">Save Tournament</button>
        </div>
    </div>

<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<h1>Tournaments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= tournament.start_date %></td>
        <td><%= tournament.end_date %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/mine.html.erb
<div ng-app="scrambledApp">
    <div class="container" ng-controller="UserTournamentController">
      <div class="col-md-2 deckHolder">
        <div class="row">
          Select a tournament:
        </div>
        <div class="row deck" ng-repeat="tournament in tournaments | orderBy:-start_date">
            <div ng-click="selectTournament(tournament)" style="text-decoration: underline">
              {{tournament.name}}
            </div>
        </div>
      </div>
      <div class="col-md-10 tournament"
           ng-class="{'active': isViewingTournament}" >
        <div>

          <h2>{{selectedTournament.name}}</h2>

        </div>
        <div ng-show="beforeStartDate">
          <h3>
            Team selection for this tournament has not started quite yet.
            Please check back after {{selectedTournament.picks_start | date: 'medium'}} </h3>
        </div>
        <div ng-show="pickingTime">
					
          <h4>Make your picks below (you have until {{selectedTournament.picks_end | date: 'medium'}}):</h4>
          <h5 class="text-danger">** Don't forget to submit your entry fee ($10) to tmilyard@gmail.com via <a href="https://paypal.com" target="_new">PayPal</a>.  
						Entries without fees paid by tournament start will be deleted.</h5>
          <form role="form" class="form-horizontal" >
            <input type="hidden" name="tournament_id" value="{{selectedTournament.id}}"/>
						<div class="row">
							<div class="col-md-5 col-sm-12 col-xs-12">
								<div class="form-group">
									<label for="agolfer" class="control-label">"A" Golfer:</label>
									<select class="form-control" ng-model="invite.agolfer" ng-options="g.player as g.player for g in agolfers" required="true"></select>

								</div>
							</div>
							<div class="col-md-5 col-md-offset-1 col-sm-offset-0 col-xs-offset-0 col-sm-12 col-xs-12">
								<div class="form-group">
									<label for="bgolfer" class="control-label">"B" Golfer:</label>
									<select class="form-control" ng-model="invite.bgolfer" ng-options="g.player as g.player for g in bgolfers" required="true"></select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-5 col-sm-12 col-xs-12">
								<div class="form-group">
									<label for="cgolfer" class="control-label">"C" Golfer:</label>
									<select class="form-control" ng-model="invite.cgolfer" ng-options="g.player as g.player for g in cgolfers" required="true"></select>
								</div>
							</div>
							<div class="col-md-5 col-md-offset-1 col-sm-offset-0 col-xs-offset-0 col-sm-12 col-xs-12">
								<div class="form-group">
									<label for="dgolfer" class="control-label">"D" Golfer:</label>
									<select class="form-control" ng-model="invite.dgolfer" ng-options="g.player as g.player for g in dgolfers" required="true"></select>
								</div>
							</div>
						</div>
						<div class="row">
            <button class="btn btn-primary" ng-click="submitGolfers(invite)">Submit</button>
						</div>
          </form>
					<p style="font-weight: bold; color: green">{{message}}</p>
        </div>
        <div ng-show="showStandings">
	  			<p class="text-danger"><b>Note:</b> {{selectedTournament.message}}</p>
          <h4>Current Standings:</h4>
          <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">

            </div>
            <div class="col-md-2 col-sm-2 col-xs-2">
              "A" Golfer
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2">
              "B" Golfer
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2">
              "C" Golfer
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2">
              "D" Golfer
            </div>
            <div class="col-md-1 col-sm-1 col-xs-1">
              Total
            </div>
          </div>
        <div ng-repeat="player in standings | orderBy:'totalScore'" class="row standingRow" ng-class-odd="'standingOddRow'">
          <div class="col-md-3 col-sm-3 col-xs-3">
            {{player.name}}
          </div>
          <div class="col-md-2 col-sm-2 col-xs-2 golferScore" ng-class="{cutGolfer: player.agolferStatus === 'cut'}">
            {{player.agolfer}} ({{player.agolferScore}}<span ng-if="player.agolferThru && player.agolferStatus !== 'cut'">, {{ player.agolferThru}}</span>)
          </div>
          <div class="col-md-2 col-sm-2 col-xs-2 golferScore" ng-class="{cutGolfer: player.bgolferStatus === 'cut'}">
            {{player.bgolfer}} ({{player.bgolferScore}}<span ng-if="player.bgolferThru && player.bgolferStatus !== 'cut'">, {{ player.bgolferThru}}</span>)
          </div>
          <div class="col-md-2 col-sm-2 col-xs-2 golferScore" ng-class="{cutGolfer: player.cgolferStatus === 'cut'}">
            {{player.cgolfer}} ({{player.cgolferScore}}<span ng-if="player.cgolferThru && player.cgolferStatus !== 'cut'">, {{ player.cgolferThru}}</span>)
          </div>
          <div class="col-md-2 col-sm-2 col-xs-2 golferScore" ng-class="{cutGolfer: player.dgolferStatus === 'cut'}">
            {{player.dgolfer}} ({{player.dgolferScore}}<span ng-if="player.dgolferThru && player.dgolferStatus !== 'cut'">, {{ player.dgolferThru}}</span>)
          </div>
          <div class="col-md-1 col-sm-1 col-xs-1">
            {{ player.totalScore }}
          </div>
        </div>


        </div>
      </div>
    </div>
</div>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<div class="container">
  <div class="col-md-12">
    <h2><%= @tournament.name %></h2>
    <table class="table">
      <tr>
        <th>Start Date</th><td><%= @tournament.start_date %></td>
        <th>End Date</th><td><%= @tournament.end_date %></td>
      </tr>
      <tr>
        <th>Picking Starts</th><td><%= @tournament.picks_start.in_time_zone("America/Chicago").strftime("%Y-%m-%d %I:%M %p %Z") %></td>
        <th>Picking Cut-off</th><td><%= @tournament.picks_end.in_time_zone("America/Chicago").strftime("%Y-%m-%d %I:%M %p %Z") %></td>
      </tr>
      <tr>
        <th>Secret Code</th><td><%= @tournament.secret_code %></td><th>Leaderboard</th><td><%= @tournament.leaderboard_url %></td>
      </tr>
      <tr>
        <th>Course Par</th><td><%= @tournament.par %></td>
        <th>Message</th><td><%= @tournament.message %></td>
      </tr>
    </table>
  </div>
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
        <% if @tournament.golfers.size == 0 %>
          <%= link_to "Freeze Golfers", freeze_golfers_tournament_path(@tournament), :class=>"btn btn-lg btn-success"%>
        <% else %>
          <h3>Golfers have been set.</h3>
          <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#playerModal">
            Show Golfers
          </button>
          <div class="modal fade" id="playerModal" tabindex="-1" role="dialog" aria-labelledby="playerModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title" id="playerModalLabel">Golfers</h4>
                </div>
                <div class="modal-body">
                   <table class="table table-striped">
                     <% @tournament.golfers.each do |g| %>
                     <tr>
                       <td><%= g.rank %></td>
                       <td><%= g.player %></td>
                     </tr>
                     <% end %>
                   </table>
                </div>
                <div class="modal-footer">
                  <button class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
          <%= link_to "Re-Freeze Golfers", freeze_golfers_tournament_path(@tournament), :class=>"btn btn-lg btn-success"%>

        <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <h3>Invited Users</h3>
    <table class="table table-striped">
        <thead>
            <tr>
              <th>Name</th>
              <th>Email Address</th>
              <th>Accepted?</th>
            </tr>
        </thead>
        <tbody>
            <% @tournament.tournament_invitations.sort_by!{|x| x.accepted? ? 0 : 1}.each do |ti| %>
            <tr>
              <td><%= ti.user.first_name %> <%= ti.user.last_name %></td>
              <td><%= ti.user.email %></td>
              <td><%= ti.accepted? %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
  </div>
  <div class="col-md-6">
    <%= form_tag invite_users_tournament_path(@tournament.id) do -%>
    <h3>Uninvited Users</h3>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email Address</th>
        <th>Invite</th>
      </tr>
      </thead>
      <tbody>
      <% if @uninvited_users.size > 0 %>

      <% @uninvited_users.each do |ui| %>
          <tr>
            <td><%= ui.first_name %> <%= ui.last_name %></td>
            <td><%= ui.email %></td>
            <td><%= check_box_tag "invite[#{ui.id}]", "yes" %> </td>
          </tr>
      <% end %>
        <tr>
          <td></td>
          <td></td>
          <td><input type="submit" value="Send Invites" class="btn btn-success"></td>
        </tr>

      <% else %>
          <tr>
            <td colspan="3" class="alert alert-error">No users exist to invite.</td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <% end -%>
  </div>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>


</div>