config/routes.rb
Scrambled::Application.routes.draw do
  get "ranked_golfer/index"
  get "ranked_golfer/reset"
  devise_for :admins
  devise_for :users

  resources :tournaments do
    collection do
      get 'upcoming'
      get 'current'
      get 'previous'
      get 'user_tournaments'
      get 'mine'
    end
    member do
      get 'uninvited_users'
      post 'invite_users'
      get 'freeze_golfers'
      get 'agolfers'
      get 'bgolfers'
      get 'cgolfers'
      get 'dgolfers'
      post 'update_invitation_with_golfers'
      get 'user_tournament_invitation'
      get 'standings'
    end
  end

  get 'invitation/accept/:id', to: 'accept_invitation#index', as: :accept_invitations
  get 'invitation/open', to: 'accept_invitation#open_user_invites', as: :open_user_invitations
  post 'invitation/accept_via_secret', to: 'accept_invitation#accept_via_secret', as: :accept_via_secret
  get 'rankings', to: 'ranked_golfer#index', as: :current_rankings
  get 'ranked_golfers', to: 'ranked_golfer#list'
  get 'reset_ranks', to: 'ranked_golfer#reset'
  get '/templates/:path.html' => 'templates#template', :constraints => {:path => /.+/}
  root :to => 'visitors#new'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if admin_signed_in? %>
        <li><%= link_to "Welcome, #{current_admin.first_name} (Log Out)", destroy_admin_session_path, :method => :delete %></li>
      <% elsif user_signed_in? %>
        <li><%= link_to "Welcome, #{current_user.first_name} (Log Out)", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Don't have an account?  Sign Up!", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? or admin_signed_in? %>
    <li><%= link_to "World Rankings", current_rankings_path %></li>
<% end %>
<% if user_signed_in? %>
    <li><%= link_to "My Tournaments", "/tournaments/mine" %></li>
<% end %>

<% if admin_signed_in? %>
    <li class="navbar-brand">Admin Menu: </li>
    <li><%= link_to "Tournaments", tournaments_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scrambled" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Scrambled" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>


    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>